name: Java CI with Ant

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive # Penting untuk menarik folder lib/

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: ant

    - name: Ambil Library AI2
      run: |
        chmod +x upgrade-appinventor.sh
        ./upgrade-appinventor.sh

    - name: Build Extension
      run: ant extensions

    - name: Upload AIX ke Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TamodaLauncher-AIX
        path: out/*.aix
